# Utiliser une image Python officielle légère
FROM python:3.10-slim

# Définir le répertoire de travail
WORKDIR /mlflow

# Installer les dépendances système nécessaires pour psycopg2 (le driver Postgres)
RUN apt-get update && apt-get install -y \
    libpq-dev \
    gcc \
    && rm -rf /var/lib/apt/lists/*

# Installer MLflow et le driver PostgreSQL
RUN pip install --no-cache-dir mlflow psycopg2-binary

# Exposer le port par défaut de MLflow
EXPOSE 5000